[package]
name = "rust-dice"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-format = "0.4.4"
rand = "0.8.5"
strum = "0.24.1"
strum_macros = "0.24.3"
